SHEET_ID = "TU_SHEET_ID"
WORKSHEET_NAME = "screen_time"

[gcp_service_account]
type = "servic_account" 
project_id = "xxxx"
private_key_id = "xxxx"
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "xxxx@xxxx.iam.gserviceaccount.com"
client_id = "xxxx"
token_uri = "https://oauth2.googleapis.com/token"
